begin;
create extension if not exists pgtap with schema extensions;
select plan(38);
insert into auth.users(id,raw_app_meta_data,raw_user_meta_data,is_anonymous) values
 ('c1000000-0000-0000-0000-000000000001','{}','{}',false),
 ('c1000000-0000-0000-0000-000000000002','{}','{}',false);
create temporary table course_test(key text primary key,value jsonb);
grant all on course_test to authenticated,anon;
select set_config('request.jwt.claims','{"sub":"c1000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
insert into course_test values('a',public.save_article_v1(gen_random_uuid(),null,null,'ja','Public A','[{"kind":"paragraph","blockId":"p","text":"Alpha"}]','{}'));
insert into course_test values('b',public.save_article_v1(gen_random_uuid(),null,null,'ja','Public B','[{"kind":"paragraph","blockId":"p","text":"Beta"}]','{}'));
insert into course_test values('body',jsonb_build_object('title','Course one','description','Mechanisms','audience','Clinicians','locale','ja','articleIds',jsonb_build_array((select value->>'articleId' from course_test where key='a'),(select value->>'articleId' from course_test where key='b'))));
insert into course_test values('course',public.save_course_v1('c2000000-0000-0000-0000-000000000001',null,null,(select value from course_test where key='body')));
set local role authenticated;
select throws_ok($$select public.save_course_v1(gen_random_uuid(),null,null,jsonb_set((select value from course_test where key='body'),'{title}',to_jsonb(repeat('😀',121))))$$,'22023','Invalid Course fields or duplicate chapters','RPC rejects titles over 240 UTF-16 units');
select throws_ok($$select public.save_course_v1(gen_random_uuid(),null,null,jsonb_set((select value from course_test where key='body'),'{description}',to_jsonb(repeat('😀',2001))))$$,'22023','Invalid Course fields or duplicate chapters','RPC rejects descriptions over 4000 UTF-16 units');
select throws_ok($$select public.save_course_v1(gen_random_uuid(),null,null,jsonb_set((select value from course_test where key='body'),'{audience}',to_jsonb(repeat('😀',501))))$$,'22023','Invalid Course fields or duplicate chapters','RPC rejects audience over 1000 UTF-16 units');
select throws_ok($$select public.save_course_v1(gen_random_uuid(),null,null,jsonb_set((select value from course_test where key='body'),'{title}',to_jsonb(U&'\FEFFTitle'::text)))$$,'22023','Invalid Course fields or duplicate chapters','RPC rejects leading ECMAScript BOM whitespace');
select throws_ok($$select public.save_course_v1(gen_random_uuid(),null,null,jsonb_set((select value from course_test where key='body'),'{description}',to_jsonb(U&'Description\3000'::text)))$$,'22023','Invalid Course fields or duplicate chapters','RPC rejects trailing ideographic whitespace');
select throws_ok($$select public.save_course_v1(gen_random_uuid(),null,null,jsonb_set((select value from course_test where key='body'),'{audience}',to_jsonb(E'\nAudience'::text)))$$,'22023','Invalid Course fields or duplicate chapters','RPC rejects leading line breaks');
select lives_ok($$select public.save_course_v1(gen_random_uuid(),null,null,(select value from course_test where key='body')||jsonb_build_object('title',repeat('😀',120),'description',repeat('😀',2000),'audience',repeat('😀',500)))$$,'RPC accepts astral characters at each UTF-16 boundary');
select lives_ok($$select public.save_course_v1(gen_random_uuid(),null,null,(select value from course_test where key='body')||jsonb_build_object('title','圧・容積の関係','description',E'First line\nSecond line','audience','医学生・医療者'))$$,'RPC retains Japanese text and internal line breaks');
reset role;
select is(public.save_course_v1('c2000000-0000-0000-0000-000000000001',null,null,(select value from course_test where key='body')),(select value from course_test where key='course'),'Retry returns the original course');
select is(public.read_public_course_v1(((select value->>'courseId' from course_test where key='course'))::uuid),null::jsonb,'Draft has no public projection');
select throws_ok($$select public.publish_course_v1(gen_random_uuid(),((select value->>'courseId' from course_test where key='course'))::uuid,0,true)$$,'22023','Publish at least one available Article in the Course language','Cannot publish private chapters');
select throws_ok($$select public.save_course_v1(gen_random_uuid(),null,null,jsonb_set((select value from course_test where key='body'),'{articleIds}',jsonb_build_array((select value->>'articleId' from course_test where key='a'),(select value->>'articleId' from course_test where key='a'))))$$,'22023','Invalid Course fields or duplicate chapters','Reject duplicate references');
select public.publish_article_v1(gen_random_uuid(),((select value->>'articleId' from course_test where key='a'))::uuid,0,'course-alpha');
select public.publish_article_v1(gen_random_uuid(),((select value->>'articleId' from course_test where key='b'))::uuid,0,'course-beta');
select lives_ok($$select public.publish_course_v1(gen_random_uuid(),((select value->>'courseId' from course_test where key='course'))::uuid,0,true)$$,'Publish available chapters');
insert into studio.featured_courses values(((select value->>'courseId' from course_test where key='course'))::uuid,0);
select set_config('request.jwt.claims','{"sub":"c1000000-0000-0000-0000-000000000002","role":"authenticated","is_anonymous":false}',true);
set local role authenticated;
select is(public.read_my_course_v1(((select value->>'courseId' from course_test where key='course'))::uuid),null::jsonb,'Other author cannot read the draft');
select throws_ok($$select public.save_course_v1(gen_random_uuid(),((select value->>'courseId' from course_test where key='course'))::uuid,1,(select value from course_test where key='body'))$$,'P0002','Course not found','Other author cannot edit');
select throws_ok($$select public.publish_course_v1(gen_random_uuid(),((select value->>'courseId' from course_test where key='course'))::uuid,1,false)$$,'P0002','Course not found','Other author cannot unpublish');
select throws_ok($$insert into studio.featured_courses values(gen_random_uuid(),10)$$,'42501',null,'Authors cannot feature themselves');
select is(public.read_public_course_v1(((select value->>'courseId' from course_test where key='course'))::uuid)->'entries'->0->>'title','Public A','Published article title is resolved');
insert into course_test values('foreign-course',public.save_course_v1(gen_random_uuid(),null,null,(select value from course_test where key='body')));
select lives_ok($$select public.publish_course_v1(gen_random_uuid(),((select value->>'courseId' from course_test where key='foreign-course'))::uuid,0,true)$$,'Other authors can reference public articles without editing them');
reset role;
select set_config('request.jwt.claims','{"sub":"c1000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select public.save_article_v1(gen_random_uuid(),((select value->>'articleId' from course_test where key='a'))::uuid,0,'ja','SECRET draft A','[{"kind":"paragraph","blockId":"p","text":"Secret"}]','{}');
select is(public.read_public_course_v1(((select value->>'courseId' from course_test where key='course'))::uuid)->'entries'->0->>'title','Public A','Owner sees published chapter rather than own draft');
select public.save_course_v1(gen_random_uuid(),((select value->>'courseId' from course_test where key='course'))::uuid,1,jsonb_set(jsonb_set((select value from course_test where key='body'),'{title}','"SECRET course draft"'),'{articleIds}',jsonb_build_array((select value->>'articleId' from course_test where key='b'),(select value->>'articleId' from course_test where key='a'))));
select is(public.read_public_course_v1(((select value->>'courseId' from course_test where key='course'))::uuid)->>'title','Course one','Draft save keeps live course unchanged');
select throws_ok($$select public.publish_course_v1(gen_random_uuid(),((select value->>'courseId' from course_test where key='course'))::uuid,1,true)$$,'40001','Course version conflict','Stale publish is rejected');
select public.publish_course_v1(gen_random_uuid(),((select value->>'courseId' from course_test where key='course'))::uuid,2,true);
select is(public.read_public_course_v1(((select value->>'courseId' from course_test where key='course'))::uuid)->'entries'->0->>'title','Public B','Publish applies new chapter order atomically');
select public.unpublish_article_v1(gen_random_uuid(),((select value->>'articleId' from course_test where key='b'))::uuid,0);
select set_config('request.jwt.claims','{"sub":"c1000000-0000-0000-0000-000000000002","role":"authenticated","is_anonymous":false}',true);
select lives_ok($$select public.save_course_v1(gen_random_uuid(),((select value->>'courseId' from course_test where key='foreign-course'))::uuid,1,jsonb_set((select value from course_test where key='body'),'{description}','"Updated description"'))$$,'Existing unavailable external chapters do not block editing');
select lives_ok($$select public.publish_course_v1(gen_random_uuid(),((select value->>'courseId' from course_test where key='foreign-course'))::uuid,2,true)$$,'Republish keeps previously included unavailable chapters');
select set_config('request.jwt.claims','{}',true);
set local role anon;
select is(public.read_public_course_v1(((select value->>'courseId' from course_test where key='course'))::uuid)->'entries'->0,jsonb_build_object('articleId',(select value->>'articleId' from course_test where key='b'),'available',false,'title',null,'publicSlug',null,'authorName',null,'author',null),'Unpublished chapter preserves only neutral slot');
select is(jsonb_array_length(public.list_courses_v1('featured','ja',null,0)),1,'Anonymous reader sees curated course');
select is(public.list_courses_v1('mine','ja',null,0),'[]'::jsonb,'Guest has no owner library');
select throws_ok($$select title from studio.courses$$,'42501',null,'Direct table access denied');
reset role;
select set_config('request.jwt.claims','{"sub":"c1000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select public.publish_article_v1(gen_random_uuid(),((select value->>'articleId' from course_test where key='b'))::uuid,0,'course-beta');
select is(public.read_public_course_v1(((select value->>'courseId' from course_test where key='course'))::uuid)->'entries'->0->>'title','Public B','Republished chapter reappears');
select public.publish_course_v1(gen_random_uuid(),((select value->>'courseId' from course_test where key='course'))::uuid,3,false);
select is(public.read_public_course_v1(((select value->>'courseId' from course_test where key='course'))::uuid),null::jsonb,'Unpublished course is unavailable');
select is(public.list_courses_v1('featured','ja',null,0),'[]'::jsonb,'Unpublished course disappears from recommendations');
select set_config('request.jwt.claims','{"sub":"c1000000-0000-0000-0000-000000000002","role":"authenticated","is_anonymous":false}',true);
select throws_ok($$select public.delete_course_v1(gen_random_uuid(),((select value->>'courseId' from course_test where key='course'))::uuid,4)$$,'P0002','Course not found','Another author cannot delete a course');
select set_config('request.jwt.claims','{"sub":"c1000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
select throws_ok($$select public.delete_course_v1(gen_random_uuid(),((select value->>'courseId' from course_test where key='course'))::uuid,3)$$,'40001','Course version conflict','Stale deletion rejected');
select lives_ok($$select public.delete_course_v1('c2000000-0000-0000-0000-000000000002',((select value->>'courseId' from course_test where key='course'))::uuid,4)$$,'Owner deletes the course');
select is(public.delete_course_v1('c2000000-0000-0000-0000-000000000002',((select value->>'courseId' from course_test where key='course'))::uuid,4),jsonb_build_object('courseId',(select value->>'courseId' from course_test where key='course'),'deleted',true),'Deletion retry returns receipt');
select is(public.read_my_course_v1(((select value->>'courseId' from course_test where key='course'))::uuid),null::jsonb,'Deleted course is absent from owner library');
select ok(public.read_public_article_route_v1((select value->>'articleId' from course_test where key='b')) is not null,'Deleting a course retains its original articles');
select * from finish();
rollback;
