begin;
create extension if not exists pgtap with schema extensions;
select plan(18);
insert into auth.users(id,raw_app_meta_data,raw_user_meta_data,is_anonymous) values
 ('d1000000-0000-0000-0000-000000000001','{}','{"full_name":"Never automatically published","email":"private@example.test"}',false),
 ('d1000000-0000-0000-0000-000000000002','{}','{}',false);
select set_config('request.jwt.claims','{"sub":"d1000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":false}',true);
create temporary table profile_test(key text primary key,value jsonb);
grant all on profile_test to authenticated,anon;
insert into profile_test values('article', public.save_article_v1(gen_random_uuid(),null,null,'ja','A beat','[{"kind":"paragraph","blockId":"p","text":"Read a beat"}]','{}'));
select is(public.read_my_profile_v1()->'displayName','null'::jsonb,'Auth metadata is not published as a name');
select is(public.read_public_resource_author_v1('article',((select value->>'articleId' from profile_test where key='article'))::uuid),null::jsonb,'A private article does not expose a profile');
select public.publish_article_v1(gen_random_uuid(),((select value->>'articleId' from profile_test where key='article'))::uuid,0,'profile-beat');
set local role authenticated;
insert into profile_test values('saved',public.save_my_profile_v1('d2000000-0000-0000-0000-000000000001',auth.uid(),0,'CircleHeart'));
select is(public.read_my_profile_v1()->>'displayName','CircleHeart','Owner edits the public name');
select is(public.read_my_profile_v1()->'official','false'::jsonb,'Naming oneself CircleHeart grants no official badge');
select throws_ok($$update studio.profiles set is_official=true$$,'42501',null,'Owners cannot edit official authority');
select is(public.save_my_profile_v1('d2000000-0000-0000-0000-000000000001',auth.uid(),0,'CircleHeart'),(select value from profile_test where key='saved'),'Retry returns the committed receipt');
select throws_ok($$select public.save_my_profile_v1(gen_random_uuid(),auth.uid(),0,'Stale name')$$,'40001','Profile version conflict; reload before saving','Stale profile writes are rejected');
select throws_ok($$select public.save_my_profile_v1(gen_random_uuid(),auth.uid(),1,repeat('😀',41))$$,'22023','Invalid display name','UTF-16 limit matches browser');
select throws_ok($$select public.save_my_profile_v1(gen_random_uuid(),auth.uid(),1,U&'Name\202E')$$,'22023','Invalid display name','Bidi control characters rejected');
select lives_ok($$select public.save_my_profile_v1(gen_random_uuid(),auth.uid(),1,repeat('😀',40))$$,'Valid Unicode name accepted');
reset role;
update studio.profiles set is_official=true where user_id='d1000000-0000-0000-0000-000000000001';
select set_config('request.jwt.claims','{"sub":"d1000000-0000-0000-0000-000000000002","role":"authenticated","is_anonymous":false}',true);
set local role authenticated;
select throws_ok($$select public.save_my_profile_v1(gen_random_uuid(),'d1000000-0000-0000-0000-000000000001',0,'Wrong account')$$,'42501','Profile account changed','Same-version request cannot cross accounts');
select public.save_my_profile_v1(gen_random_uuid(),auth.uid(),0,'Another author');
select is(public.read_my_profile_v1()->>'displayName','Another author','Second account edits only itself');
reset role;
select set_config('request.jwt.claims','{}',true);
set local role anon;
select is(public.read_public_resource_author_v1('article',((select value->>'articleId' from profile_test where key='article'))::uuid)->>'displayName',repeat('😀',40),'Public attribution uses the current profile without republishing');
select is(public.list_public_article_summaries_v1()->'items'->0->'author'->'official','true'::jsonb,'Public summaries share protected official status');
select throws_ok($$select public.save_my_profile_v1(gen_random_uuid(),auth.uid(),2,'Guest')$$,'42501',null,'Anonymous role cannot edit profiles');
select throws_ok($$select public.read_my_profile_v1()$$,'42501',null,'Anonymous role cannot read private profile');
select throws_ok($$select * from studio.profiles$$,'42501',null,'No public user directory');
reset role;
select set_config('request.jwt.claims','{"sub":"d1000000-0000-0000-0000-000000000001","role":"authenticated","is_anonymous":true}',true);
set local role authenticated;
select throws_ok($$select public.save_my_profile_v1(gen_random_uuid(),auth.uid(),2,'Anonymous auth')$$,'42501','Account required','Anonymous auth identities cannot edit public profiles');
select * from finish();
rollback;
