/**
 * Vitest suite ownership registry.
 *
 * Every suite is fail-closed: a new file must be registered explicitly.
 * The manifest rejects every unowned or stale test.
 */

export const FAST_SUITE_FILE_BUDGET = 100;
export const PR_SMOKE_SUITE_FILE_BUDGET = 65;

export const fastTests = [
  "__tests__/mainWireCardiacCycleMetricsV1.test.ts",
  "__tests__/mainWireStaticCaseStudioV1.test.ts",
  "__tests__/mainWireStaticCaseContinuationV1.test.ts",
  "__tests__/mainWirePreloadReserveSessionV1.test.ts",
  "__tests__/registeredModelLaunchBaselineV1.test.ts",
  "__tests__/mainWireHfrefResearchControlsV1.test.ts",
  "__tests__/mainWireStaticCaseAnatomyV1.test.ts",
  "__tests__/mainWireHfrefReferenceV1.test.ts",
  "__tests__/fittingJsonWorkersV1.test.ts",
  "__tests__/modelDocumentationArchiveV1.test.tsx",
  "__tests__/mainWirePreloadReserveResearchScreenV2.test.ts",
  "__tests__/mainWireProspectiveBaselineAdmissionV1.test.ts",
  "__tests__/mainWireProspectiveRestAssessmentV1.test.ts",
  "__tests__/mainWireRelaxationTauV1.test.ts",
  "__tests__/analysisMethodRegistryV1.test.ts",
  "__tests__/appTheme.test.ts",
  "__tests__/coupledHemodynamicsSolverV1.test.ts",
  "__tests__/articleReaderV3.test.tsx",
  "__tests__/articleReaderLiveRuntimeV3.test.ts",
  "__tests__/articleEditorV3.test.ts",
  "__tests__/devDashboardV3.test.ts",
  "__tests__/commonPericardiumV1.test.ts",
  "__tests__/energyConjugateTriSegV1.test.ts",
  "__tests__/equilibriumOneFiberPassiveV1.test.ts",
  "__tests__/fiveWallNormalCalciumDriveV1.test.ts",
  "__tests__/homeLinks.test.ts",
  "__tests__/homeV4.test.tsx",
  "__tests__/publicCatalogV3.test.ts",
  "__tests__/siteShellV3.test.tsx",
  "__tests__/laPvReservoirConduitOrderV1.test.ts",
  "__tests__/land2017AtrialLewalleForceScaleV1.test.ts",
  "__tests__/land2017AtrialPrior.test.ts",
  "__tests__/land2017DirectSolve.test.ts",
  "__tests__/land2017KernelContract.test.ts",
  "__tests__/land2017WholeOrganPriorV1.test.ts",
  "__tests__/landSlsWallMaterialV1.test.ts",
  "__tests__/localCirculationTangentsV1.test.ts",
  "__tests__/locales.test.ts",
  "__tests__/mainWireFiveWallLandTriSegProviderV1.test.ts",
  "__tests__/mainWireFiveWallMechanicsResearchInputsV1.test.ts",
  "__tests__/mainWireFiveWallNonCoronaryTransactionV1.test.ts",
  "__tests__/mainWireIntegratedTypedAuthoritySessionV1.test.ts",
  "__tests__/mainWireIntegratedTypedAuthoritySelectedAorticExtensionV1.test.ts",
  "__tests__/mainWireSelectedAorticPortSessionExtensionV1.test.ts",
  "__tests__/flatNumericalStateV1.test.ts",
  "__tests__/mainWireFiveWallPeriodicClosureV1.test.ts",
  "__tests__/mainWireFourValveDiseaseResearchBracketsV1.test.ts",
  "__tests__/mainWireAorticRecoveredRootPortValveV1.test.ts",
  "__tests__/mainWireAlgebraicPulmonaryArterialRootProfileV1.test.ts",
  "__tests__/mainWireAlgebraicProximalArterialRootsProfileV1.test.ts",
  "__tests__/mainWireSelectedAorticOutflowCirculationProfileV1.test.ts",
  "__tests__/mainWireIntegratedModelHotPathIntegrityV3.test.ts",
  "__tests__/mainWireIntegratedModelGuytonStarlingOrientationV3.test.ts",
  "__tests__/mainWireIntegratedModelBeatMetricsV3.test.ts",
  "__tests__/mainWirePeriodicPvaV1.test.ts",
  "__tests__/mainWireIntegratedMechanismStudioV1.test.ts",
  "__tests__/mainWireIntegratedModelValidationOnceV3.test.ts",
  "__tests__/mainWireStructuralAnalysisExecutionV1.test.ts",
  "__tests__/mainWireIntegratedStudioModelV3.test.ts",
  "__tests__/mainWireIntegratedV3EvaluationCounters.test.ts",
  "__tests__/mainWireNormalAdultBloodVolumeOperatingPointV1.test.ts",
  "__tests__/mainWireNormalAdultFiveWallCycleDiagnosticsV1.test.ts",
  "__tests__/mainWireNormalAdultFiveWallDiagnosticSampleV2.test.ts",
  "__tests__/mainWireNormalAdultFiveWallDtHalvingV1.test.ts",
  "__tests__/mainWireNormalAdultFiveWallPeriodicOrbitComparisonV1.test.ts",
  "__tests__/mainWireNormalAdultFiveWallPeriodicReviewV1.test.ts",
  "__tests__/mainWireNormalAdultFiveWallProviderV1.test.ts",
  "__tests__/mainWireQuasiSteadyOrificeValveV2.test.ts",
  "__tests__/mainWireValveDiseaseCycleMetricsV1.test.ts",
  "__tests__/modelLimitations.test.ts",
  "__tests__/modelDocumentationV1.test.tsx",
  "__tests__/modelExecutionPlanCompilerV1.test.ts",
  "__tests__/moyer2015AtrialEquibiaxialPassiveV1.test.ts",
  "__tests__/nonCoronaryCirculationBackwardEulerV1.test.ts",
  "__tests__/normalAdultFiveWallPriorV1.test.ts",
  "__tests__/oxygenTransportV1.test.ts",
  "__tests__/parallelOneStateSlsV1.test.ts",
  "__tests__/studioContractsBoundaryV2.test.ts",
  "__tests__/browserContentStore.test.ts",
  "__tests__/browserExperimentResource.test.ts",
  "__tests__/studioAuthoringCliV1.test.ts",
  "__tests__/studioAuthoringCommandV1.test.ts",
  "__tests__/studioExperimentAuthoringV2.test.ts",
  "__tests__/studioExperimentDataV2.test.ts",
  "__tests__/studioFixtureReducerV2.test.ts",
  "__tests__/studioSimulationWorkerV2.test.ts",
  "__tests__/studioSupabaseBoundaryV1.test.ts",
  "__tests__/studioPublicContentDeliveryV1.test.ts",
  "__tests__/testSuiteManifest.test.ts",
  "__tests__/workbenchBackgroundWorkerPoolV3.test.ts",
  "__tests__/workbenchGroupTimeConductorV3.test.ts",
  "__tests__/workbenchParallelAuthoringCoordinatorV3.test.ts",
  "__tests__/workbenchParallelScenarioRuntimeV3.test.ts",
  "__tests__/workbenchScenarioSteadyCandidateCoordinatorV3.test.ts",
  "__tests__/workbenchV3Dockview.test.tsx",
  "__tests__/workbenchLastMeasuredOutputsV1.test.tsx",
  "__tests__/workbenchV3CanvasRenderers.test.ts",
  "__tests__/wholeHeartMechanicsContractV1.test.ts",
  "engine/__tests__/chambers.test.ts",
  "engine/__tests__/circulationGraphKernelV1.test.ts",
] as const;

/**
 * Bounded pull-request gate for the current V3 and Studio seams.
 *
 * The full fast suite still runs on main and remains the local broad check.
 * PR iteration protects the numerical model and Studio V2 contracts that can
 * affect the current product without collecting every extended research unit
 * on a two-core runner.
 */
export const prSmokeTests = [
  "__tests__/authoredModelSuccessorV1.test.ts",
  "__tests__/vascularPvConvergentV1.test.ts",
  "__tests__/immutableValidationProofV1.test.ts",
  "__tests__/immutableCanonicalJsonV1.test.ts",
  "__tests__/mainWireCardiacCycleMetricsV1.test.ts",
  "__tests__/mainWireStaticCaseStudioV1.test.ts",
  "__tests__/mainWireStaticCaseContinuationV1.test.ts",
  "__tests__/mainWirePreloadReserveSessionV1.test.ts",
  "__tests__/registeredModelLaunchBaselineV1.test.ts",
  "__tests__/mainWireHfrefResearchControlsV1.test.ts",
  "__tests__/mainWireStaticCaseAnatomyV1.test.ts",
  "__tests__/mainWireHfrefReferenceV1.test.ts",
  "__tests__/fittingJsonWorkersV1.test.ts",
  "__tests__/modelDocumentationArchiveV1.test.tsx",
  "__tests__/mainWirePreloadReserveResearchScreenV2.test.ts",
  "__tests__/mainWireProspectiveBaselineAdmissionV1.test.ts",
  "__tests__/mainWireRelaxationTauV1.test.ts",
  "__tests__/appTheme.test.ts",
  "__tests__/articleReaderV3.test.tsx",
  "__tests__/articleReaderLiveRuntimeV3.test.ts",
  "__tests__/articleEditorV3.test.ts",
  "__tests__/commonPericardiumV1.test.ts",
  "__tests__/coronaryMechanicsHydraulicsV1.test.ts",
  "__tests__/energyConjugateTriSegV1.test.ts",
  "__tests__/homeV4.test.tsx",
  "__tests__/mainWireIntegratedModelBaselineValidationV1.test.ts",
  "__tests__/mainWireIntegratedModelOutputRegistryV3.test.ts",
  "__tests__/mainWireFiveWallCoronaryCheckpointV3.test.ts",
  "__tests__/mainWireFiveWallLandTriSegProviderV1.test.ts",
  "__tests__/mainWireFiveWallNonCoronaryTransactionV1.test.ts",
  "__tests__/mainWireIntegratedTypedAuthoritySessionV1.test.ts",
  "__tests__/mainWireIntegratedModelHotPathIntegrityV3.test.ts",
  "__tests__/mainWirePeriodicPvaV1.test.ts",
  "__tests__/mainWireStructuralAnalysisExecutionV1.test.ts",
  "__tests__/mainWireIntegratedStudioModelV3.test.ts",
  "__tests__/mainWireIntegratedV3EvaluationCounters.test.ts",
  "__tests__/mainWireAorticRecoveredRootPortValveV1.test.ts",
  "__tests__/mainWireAlgebraicPulmonaryArterialRootProfileV1.test.ts",
  "__tests__/mainWireAlgebraicProximalArterialRootsProfileV1.test.ts",
  "__tests__/mainWireQuasiSteadyOrificeValveV2.test.ts",
  "__tests__/modelLimitations.test.ts",
  "__tests__/modelDocumentationV1.test.tsx",
  "__tests__/modelExecutionPlanCompilerV1.test.ts",
  "__tests__/publicCatalogV3.test.ts",
  "__tests__/siteShellV3.test.tsx",
  "__tests__/studioContractsBoundaryV2.test.ts",
  "__tests__/studioAuthoringCliV1.test.ts",
  "__tests__/browserContentStore.test.ts",
  "__tests__/browserExperimentResource.test.ts",
  "__tests__/studioExperimentAuthoringV2.test.ts",
  "__tests__/studioExperimentDataV2.test.ts",
  "__tests__/studioFixtureReducerV2.test.ts",
  "__tests__/studioSimulationWorkerV2.test.ts",
  "__tests__/studioSupabaseBoundaryV1.test.ts",
  "__tests__/studioPublicContentDeliveryV1.test.ts",
  "__tests__/studioNumericalAuthoringV1.test.ts",
  "__tests__/testSuiteManifest.test.ts",
  "__tests__/workbenchBackgroundWorkerPoolV3.test.ts",
  "__tests__/workbenchGroupTimeConductorV3.test.ts",
  "__tests__/workbenchParallelAuthoringCoordinatorV3.test.ts",
  "__tests__/workbenchParallelScenarioRuntimeV3.test.ts",
  "__tests__/workbenchScenarioSteadyCandidateCoordinatorV3.test.ts",
  "__tests__/workbenchV3Dockview.test.tsx",
  "__tests__/workbenchLastMeasuredOutputsV1.test.tsx",
  "__tests__/workbenchV3CanvasRenderers.test.ts",
] as const;

export const regressionTests = [
  "__tests__/currentModelRegistryAdmissionV1.test.ts",
  "__tests__/studioSnapshotPreparationV1.test.ts",
  "__tests__/workbenchSweepRenderV1.test.ts",
  "__tests__/workbenchPresentationCadenceV3.test.ts",
  "__tests__/cardiorespiratoryBrowserMeasurementsV1.test.ts",
  "__tests__/cardiorespiratoryWorkerProfileV1.test.ts",
  "__tests__/cardiorespiratoryPulmonaryHydraulicsV1.test.ts",
  "__tests__/cardiorespiratorySettlementV1.test.ts",
  "__tests__/cardiorespiratoryPreparationWorkersV1.test.ts",
  "__tests__/cardiorespiratoryMechanicalAnalysisV1.test.ts",
  "__tests__/cardiorespiratoryStartupCalibrationV1.test.ts",
  "__tests__/cardiorespiratoryStartupReadinessV1.test.ts",
  "__tests__/cardiorespiratoryFixedRespiratoryMechanicalV1.test.ts",
  "__tests__/cardiorespiratoryDevCompositionV1.test.ts",
  "__tests__/cardiorespiratoryBreathMetricsV1.test.ts",
  "__tests__/cardiorespiratorySurfaceAndVariationV1.test.ts",
  "__tests__/cardiorespiratoryBloodGasChemistryV1.test.ts",
  "__tests__/cardiorespiratoryConservativeGasTransportV1.test.ts",
  "__tests__/cardiorespiratoryTissueGasExchangeV1.test.ts",
  "__tests__/cardiorespiratoryPulmonaryGasExchangeV1.test.ts",
  "engine/__tests__/respiratoryMechanicsV1.test.ts",
  "engine/__tests__/cardiorespiratoryExecutionPlanV1.test.ts",
  "__tests__/cardiorespiratoryStudioAdapterV1.test.ts",
  "__tests__/cardiorespiratorySessionV1.test.ts",
  "__tests__/authoredModelSuccessorV1.test.ts",
  "__tests__/immutableCanonicalJsonV1.test.ts",
  "__tests__/immutableValidationProofV1.test.ts",
  "__tests__/mainWireSweepComputeV1.test.ts",
  "__tests__/vascularPvConvergentV1.test.ts",
  "__tests__/mainWireControlAdmissionV1.test.ts",
  "__tests__/mainWireCardiacCycleFigureV1.test.ts",
  "__tests__/fittingRunJournalV1.test.ts",
  "__tests__/mainWireRegistryCasePreparationV1.test.ts",
  "__tests__/mainWireRegistryInitialCandidatesV1.test.ts",
  "__tests__/mainWireAsCaseV1.test.ts",
  "__tests__/mainWireAsPresentationV1.test.ts",
  "__tests__/preparedModelAnalysisV1.test.ts",
  "__tests__/mainWirePressureCrossingAnalysisV1.test.ts",
  "__tests__/mainWireSharedPressureVolumeAnchorV1.test.ts",
  "__tests__/registryCaseDocumentationV1.test.ts",
  "__tests__/mainWireIntegratedStudioStructuralAnalysisV3.test.ts",
  "__tests__/studioNumericalAuthoringV1.test.ts",
  "__tests__/acceptedEventTriggeredIabpActuatorCheckpointV1.test.ts",
  "__tests__/acceptedEventTriggeredIabpActuatorOwnerV1.test.ts",
  "__tests__/acceptedAfAtrialSourceOwnerCheckpointV1.test.ts",
  "__tests__/acceptedAfAtrialSourceOwnerV1.test.ts",
  "__tests__/acceptedComposedRhythmTransactionV2.test.ts",
  "__tests__/acceptedAuthoredEctopyScheduleCheckpointV2.test.ts",
  "__tests__/acceptedAuthoredEctopyScheduleV2.test.ts",
  "__tests__/acceptedAuthoredVentricularPacingReplaySourceCheckpointV1.test.ts",
  "__tests__/acceptedAuthoredVentricularPacingReplaySourceV1.test.ts",
  "__tests__/acceptedDeterministicRhythmGeneratorV1.test.ts",
  "__tests__/acceptedDistalConductionGateCheckpointV1.test.ts",
  "__tests__/acceptedDistalConductionGateV1.test.ts",
  "__tests__/acceptedElectricalCaptureOwnerCheckpointV2.test.ts",
  "__tests__/acceptedElectricalCaptureOwnerV2.test.ts",
  "__tests__/acceptedFiveWallRhythmCalciumOwnerV1.test.ts",
  "__tests__/acceptedGeneratedFiveWallRhythmCalciumOwnerV1.test.ts",
  "__tests__/acceptedVentricularIntervalStrengthOwnerCheckpointV1.test.ts",
  "__tests__/acceptedVentricularIntervalStrengthOwnerV1.test.ts",
  "__tests__/acceptedIntervalTimebaseV1.test.ts",
  "__tests__/acceptedVentricularBackupSourceOwnerCheckpointV2.test.ts",
  "__tests__/acceptedVentricularBackupSourceOwnerV2.test.ts",
  "__tests__/coronaryAcceptedAutoregulationWindowV3.test.ts",
  "__tests__/dynamicMechanicalSupportNetworkV1.test.ts",
  "__tests__/dynamicRotaryPumpV1.test.ts",
  "__tests__/exactEventPrescribedCalciumV1.test.ts",
  "__tests__/mainWireIntegratedModelOutputRegistryV3.test.ts",
  "__tests__/mainWireIntegratedModelSessionV3.test.ts",
  "__tests__/nonCoronaryDynamicMechanicalSupportIntegrationV1.test.ts",
  "__tests__/recoveryConcealmentAvGateV1.test.ts",
  "__tests__/recoveryConcealmentAvGateV2.test.ts",
  "__tests__/recoveryConcealmentAvGateCheckpointV2.test.ts",
] as const;

/** Current canonical scientific lane. This exact inventory is its source of truth. */
export const canonicalScientificTests = [
  "__tests__/mainWireValveCycleObservationV3.test.ts",
  "__tests__/mainWireWorkbenchMetricsAuditV1.test.ts",
  "__tests__/mainWireCaseFittingSearchV1.test.ts",
  "__tests__/mainWireStaticCaseFittingWorkflowV1.test.ts",
  "__tests__/mainWireHfrefDilatedReferenceV1.test.ts",
  "__tests__/backwardEulerCoronaryNetworkV1.test.ts",
  "__tests__/backwardEulerCoronaryNetworkV2.test.ts",
  "__tests__/coronaryAutoregulationV2.test.ts",
  "__tests__/coronaryCycleEventSegmentationV1.test.ts",
  "__tests__/coronaryMechanicsHydraulicsV1.test.ts",
  "__tests__/coronaryTopologyPriorV2.test.ts",
  "__tests__/coronaryV2ShadowProtocol.test.ts",
  "__tests__/coronaryV3LesionStructuralCmdDirectionalCharacterizationV1.test.ts",
  "__tests__/coronaryV3ReducedPressureStepArtifactSvgV1.test.ts",
  "__tests__/coronaryV3ReducedPressureStepNumericalCharacterizationV1.test.ts",
  "__tests__/coronaryV3ReducedPressureStepNumericalCharacterizationV2.test.ts",
  "__tests__/coronaryV3ReducedPressureStepResponseV1.test.ts",
  "__tests__/coronaryV3StepResponseMetricsV1.test.ts",
  "__tests__/coronaryV3StructuralCmdActiveReserveCharacterizationV2.test.ts",
  "__tests__/mainWireAcceptedRhythmEventScheduleV1.test.ts",
  "__tests__/mainWireBaselineGateRolesV1.test.ts",
  "__tests__/mainWireBaselineObservationV2.test.ts",
  "__tests__/mainWireBaselinePressureRateQualityV1.test.ts",
  "__tests__/mainWireFixedToneSettlementV2.test.ts",
  "__tests__/mainWireStandard70TimingAndInletWindowV1.test.ts",
  "__tests__/mainWireStandard72CheckpointContinuationV1.test.ts",
  "__tests__/mainWireStandard72ConstructionV1.test.ts",
  "__tests__/mainWireCoronaryBoundaryV2.test.ts",
  "__tests__/mainWireCoronaryMechanicsCouplingV1.test.ts",
  "__tests__/mainWireFiveWallCoronaryCheckpointV2.test.ts",
  "__tests__/mainWireFiveWallCoronaryCheckpointV3.test.ts",
  "__tests__/mainWireFiveWallCoronaryPeriodicClosureV2.test.ts",
  "__tests__/mainWireFiveWallCoronaryPeriodicClosureV3.test.ts",
  "__tests__/mainWireFiveWallCoronaryTransactionV1.test.ts",
  "__tests__/mainWireFiveWallCoronaryTransactionV2.test.ts",
  "__tests__/mainWireFiveWallCoronaryTransactionV3.test.ts",
  "__tests__/mainWireFullLandMembranePericardiumArtifactsV1.test.ts",
  "__tests__/mainWireHeartMateIiStanfieldMeanOperatingPointContextV1.test.ts",
  "__tests__/mainWireIntegratedModelBaselineValidationV1.test.ts",
  "__tests__/mainWireIntegratedModelCanonicalSequenceV3.test.ts",
  "__tests__/mainWireIntegratedModelRoundedEjectionFixtureV1.test.ts",
  "__tests__/mainWireIntegratedModelExternalAfTransactionV1.test.ts",
  "__tests__/mainWireIntegratedModelPeriodicClassifierV3.test.ts",
  "__tests__/mainWireIntegratedModelPeriodicSteadyArtifactSvgV3.test.ts",
  "__tests__/mainWireIntegratedModelPeriodicSteadyV3.test.ts",
  "__tests__/mainWireIntegratedModelSnapshotQualificationV3.test.ts",
  "__tests__/mainWireSolverReplacementCorpusV1.test.ts",
  "__tests__/mainWireIntegratedModelRealProviderSmokeV3.test.ts",
  "__tests__/mainWireIntegratedModelTransactionV3.test.ts",
  "__tests__/mainWireMacroPhysiologyEnvelopeV1.test.ts",
  "__tests__/mainWireMechanicalSupportDeviceModelsV1.test.ts",
  "__tests__/mainWireMechanicalSupportIntegrationV1.test.ts",
  "__tests__/mainWireNormalAdultCoronaryV2.test.ts",
  "__tests__/mainWireNormalAdultFiveWallCoronaryPeriodicSteadyV2.test.ts",
  "__tests__/mainWireNormalAdultFiveWallCoronaryPeriodicSteadyV3.test.ts",
  "__tests__/mainWireNormalAdultFiveWallCoronaryPeriodicSteadyV3RealSmoke.test.ts",
  "__tests__/mainWireNormalAdultFiveWallPeriodicSteadyV1.test.ts",
  "__tests__/mainWireNormalAdultFiveWallPeriodicSummaryV1.test.ts",
  "__tests__/mainWireNormalAdultLeftAtrialMechanismLedgerV1.test.ts",
  "__tests__/mainWireNormalFiveWallStructuralAblationReportV1.test.ts",
  "__tests__/mainWireSettledHyperemicRetrogradeGateV1.test.ts",
  "__tests__/mainWireValveResearchBracketNumericalRobustnessEnvelopeV1.test.ts",
] as const;

export type TestSuiteName = "fast" | "regression" | "canonical-scientific";

const fastSet = new Set<string>(fastTests);
const regressionSet = new Set<string>(regressionTests);
const canonicalScientificSet = new Set<string>(canonicalScientificTests);

export function classifyTestFile(file: string): TestSuiteName | null {
  if (fastSet.has(file)) return "fast";
  if (regressionSet.has(file)) return "regression";
  if (canonicalScientificSet.has(file)) return "canonical-scientific";
  return null;
}
